FROM golang:stretch as preparation
ENV GodisApiEndpoint=0.0.0.0:8090
ENV GodisBackupInterval=1h

WORKDIR /app
RUN git clone https://github.com/callduckk/YSGo .
RUN go build -o /app/GodisAPI /app/cmd 

EXPOSE 8090

FROM golang:stretch as build

WORKDIR /app
COPY --from=preparation /app/GodisAPI ./

ENTRYPOINT [ "/app/GodisAPI" ]
