on:
  push:
    branches:
      - main

jobs:
  build:
    
    runs-on: ubuntu-latest

    steps:

    - name: Execute git clone and docker-compose up
      uses: appleboy/ssh-action@master
      with:
        HOST: ${{ secrets.HOST }}
        USERNAME: ${{ secrets.USERNAME }}
        PORT: ${{ secrets.PORT }}
        KEY: ${{ secrets.SSHKEY }}
        script: |
          rm -rf /home/${{ secrets.USERNAME }}/YSGo-NginxReverseProxy
          git clone https://github.com/callduckk/YSGo-nginxReverseProxy.git /home/${{ secrets.USERNAME }}/YSGo-NginxReverseProxy
          cd /home/${{ secrets.USERNAME }}/YSGo-NginxReverseProxy
          sudo docker-compose up --detach
          rm -rf /home/${{ secrets.USERNAME }}/GodisAPI
          mkdir /home/${{ secrets.USERNAME }}/GodisAPI
          cd /home/${{ secrets.USERNAME }}/GodisAPI
          curl -O https://raw.githubusercontent.com/callduckk/YSGo/main/Dockerfile.production
          curl -O https://raw.githubusercontent.com/callduckk/YSGo/main/docker-compose.yml
          sudo docker-compose up --detach